//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü: 4.0.30319.42000
//
//     Bu dosyada yapılan değişiklikler yanlış davranışa yol açabilir ve şu durumda kaybolur
//     kod yeniden oluşturulduğunda.
// </auto-generated>
//------------------------------------------------------------------------------


namespace modbus_plc_grafik.Properties
{
    /// <summary>
    ///   Yerelleştirilmiş dizeleri vs. aramak için türü kesin belirlenmiş bir kaynak sınıfı.
    /// </summary>
    // Bu sınıf, StronglyTypedResourceBuilder tarafından otomatik olarak
    // ResGen ya da Visual Studio gibi bir araç ile oluşturuldu.
    // Bir üye eklemek ya da kaldırmak için .ResX dosyanızı düyenleyin, sonra da ResGen
    // öğesini /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden derleyin.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("modbus_plc_grafik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Geçerli iş parçacığının CurrentUICulture özelliğini, türü kesin belirlenmiş
        ///   bu kaynak sınıfını kullanan tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string Acknowlege
        {
            get
            {
                return ResourceManager.GetString("Acknowlege", resourceCulture);
            }
        }

        /// <summary>
        ///   Argument endPoint cannot be empty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EmptyEndPoint
        {
            get
            {
                return ResourceManager.GetString("EmptyEndPoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Specialized use in conjunction with gateways, indicates that the gateway was unable to allocate an internal communication path from the input port to the output port for processing the request. Usually means that the gateway is misconfigured or overloaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GatewayPathUnavailable
        {
            get
            {
                return ResourceManager.GetString("GatewayPathUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Specialized use in conjunction with gateways, indicates that no response was obtained from the target device. Usually means that the device is not present on the network. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GatewayTargetDeviceFailedToRespond
        {
            get
            {
                return ResourceManager.GetString("GatewayTargetDeviceFailedToRespond", resourceCulture);
            }
        }

        /// <summary>
        ///   Hex string must have even number of characters. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HexCharacterCountNotEven
        {
            get
            {
                return ResourceManager.GetString("HexCharacterCountNotEven", resourceCulture);
            }
        }

        /// <summary>
        ///   The data address received in the query is not an allowable address for the server (or slave). More specifically, the combination of reference number and transfer length is invalid. For a controller with 100 registers, the PDU addresses the first register as 0, and the last one as 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 4, then this request will successfully operate (address-wise at least) on registers 96, 97, 98, 99. If a request is submitted with  [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IllegalDataAddress
        {
            get
            {
                return ResourceManager.GetString("IllegalDataAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   A value contained in the query data field is not an allowable value for server (or slave). This indicates a fault in the structure of the remainder of a complex request, such as that the implied length is incorrect. It specifically does NOT mean that a data item submitted for storage in a register has a value outside the expectation of the application program, since the MODBUS protocol is unaware of the significance of any particular value of any particular register. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IllegalDataValue
        {
            get
            {
                return ResourceManager.GetString("IllegalDataValue", resourceCulture);
            }
        }

        /// <summary>
        ///   The function code received in the query is not an allowable action for the server (or slave). This may be because the function code is only applicable to newer devices, and was not implemented in the unit selected. It could also indicate that the server (or slave) is in the wrong state to process a request of this type, for example because it is unconfigured and is being asked to return register values. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IllegalFunction
        {
            get
            {
                return ResourceManager.GetString("IllegalFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Specialized use in conjunction with function codes 20 and 21 and reference type 6, to indicate that the extended file area failed to pass a consistency check. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MemoryParityError
        {
            get
            {
                return ResourceManager.GetString("MemoryParityError", resourceCulture);
            }
        }

        /// <summary>
        ///   Array networkBytes must contain an even number of bytes. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NetworkBytesNotEven
        {
            get
            {
                return ResourceManager.GetString("NetworkBytesNotEven", resourceCulture);
            }
        }

        /// <summary>
        ///   Specialized use in conjunction with programming commands. The server (or slave) is engaged in processing a long–duration program command. The client (or master) should retransmit the message later when the server (or slave) is free. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlaveDeviceBusy
        {
            get
            {
                return ResourceManager.GetString("SlaveDeviceBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   An unrecoverable error occurred while the server (or slave) was attempting to perform the requested action. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlaveDeviceFailure
        {
            get
            {
                return ResourceManager.GetString("SlaveDeviceFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Function Code: {1}{0}Exception Code: {2} - {3} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlaveExceptionResponseFormat
        {
            get
            {
                return ResourceManager.GetString("SlaveExceptionResponseFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Invalid function code value for SlaveExceptionResponse. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SlaveExceptionResponseInvalidFunctionCode
        {
            get
            {
                return ResourceManager.GetString("SlaveExceptionResponseInvalidFunctionCode", resourceCulture);
            }
        }

        internal static string TimeoutNotSupported
        {
            get
            {
                return ResourceManager.GetString("TimeoutNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   UdpClient must be bound to a default remote host. Call the Connect method. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UdpClientNotConnected
        {
            get
            {
                return ResourceManager.GetString("UdpClientNotConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Unknown slave exception code. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Unknown
        {
            get
            {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }

        internal static string WaitRetryGreaterThanZero
        {
            get
            {
                return ResourceManager.GetString("WaitRetryGreaterThanZero", resourceCulture);
            }
        }
    }
}
